sonar.projectKey=pravin-tasklist-backend
sonar.projectName=pravin-tasklist-backend
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr
sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts
sonar.exclusions=**/node_modules/**